andreev_homework_19
eugene-okulik/Makeim pull request #18
Opened 2024-05-23 21:35 UTC by CheMaks1

Немного не понял только почему удаление не поругалось, т.к. после выполнения удаления в test_delete_a_post, он должен вернуться к фикстуре, где после йелда он удаляет снова, а тут получается что он попытается удалить, а удалять уже нечего

2024-05-24 13:15 UTC, eugene-okulik requested changes
А он просто получил 404 и всё. Если не сказать, что ты ждешь статус 200, то все нормально и пройдет. И это ок.  
А вот не ок, что нет теста на создание объекта.

2024-05-24 15:47 UTC, CheMaks1 commented
Добавил проверку.

2024-05-26 14:43 UTC, eugene-okulik requested changes
Всё еще нет теста на создание объекта.

2024-05-29 07:42 UTC, CheMaks1 commented
А сейчас?

2024-05-30 09:45 UTC, eugene-okulik requested changes
И сейчас нет теста на создание объекта. Ты добавляешь проверки в фикстуру, но не создаешь тест.

2024-06-01 18:20 UTC, CheMaks1 commented
А так? Я просто не знаю, как-будто не понимаю о чём речь.

2024-06-03 09:24 UTC, eugene-okulik approved these changes
Теперь да, добавил. Тест - это функция, которая начинается на `test_`  
Фикстура, которая создает объект - это только фикстура, так как тест не может быть одновременно и фикстурой и тестом. Пока что это рождает повторение одного и того же кода, но чуть позже мы от этого избавимся.

2024-06-03 09:24 UTC, merged