Andeev homework 21
eugene-okulik/Makeim pull request #20
Opened 2024-08-17 14:57 UTC by CheMaks1

Более чем уверен, что там будут правки, посмотрите плз) запутался что ещё нужно сделать, хотя вроде всё красиво, всё запускается, мучался пол дня с фейлами, тут недописал, тут ошибся, тут ещё что-то, но в итоге всё passed, но как-будто чего-то не хватает
Сейчас было больше работы, чем обычно, поэтому я ещё месяц отсутствовал)) больше такого не будет 100% ))

2024-08-18 13:59 UTC, eugene-okulik requested changes

2024-08-18 13:59 UTC, eugene-okulik commented on test_api_mandreevproj/conftest.py
> +    return DeletePost()
Судя по названиям, ты создаешь, апдейтишь, удаляешь какие-то посты. Но в апишке же мы создаем объекты (или гаджеты или товары), но не посты. Это в той апишке, которая была на занятии я тестировал типа апишку соцсети, а в соцсети создаются посты (они же - публикации).  
В автотестах очень важно давать такие названия всему, чтобы было понятно что скрывается под этим названием.

2024-08-18 13:59 UTC, eugene-okulik commented on test_api_mandreevproj/endpoints/create_post.py
> +        assert self.response.status_code == 400, '400 is not 400'
Статус 400 мы будем проверять у всех эндпоинтов, если будем полноценные тесты писать. Этот метод можно было вынести в класс Endpoint.

2024-08-18 13:59 UTC, eugene-okulik commented on test_api_mandreevproj/endpoints/endpoint.py
> +        assert self.response.status_code == 200, '200 is not 200'
Здесь тоже приколупаюсь к названию. Прикинь, у тебя есть такой ручной тест:
1. Выполнить запрос
2. Проверить статус код

Я проверил - он 203, или 400, или 502. Он есть. Всё ок ))) Хорошо бы, чтобы из шага теста было понятно что в нем происходит. название check_response_status_code_is_200 уже лучше.

2024-08-18 13:59 UTC, eugene-okulik commented on test_api_mandreevproj/tests/test_rfad.py
> +    response = create_post_endpoint.create_new_post(payload=data)
Создание объекта не является шагом теста. Это его предусловие. А предусловия мы оформляем в фикстурах.

2024-08-20 20:56 UTC, CheMaks1 commented
Честно говоря переделал всё, кроме 4 пункта. И даже заметил ошибку, что я в функции с путом использовал захардкоженый юрл.
Вопрос по 4му пункту - не понимаю как мне его оформить, ломал над этим голову.
Не понимаю что и куда добавить. К уже имеющимся фикстурам добавить ещё одну, или как..запутался

2024-08-21 06:44 UTC, CheMaks1 commented
Думал думал, и придумал. Так красивее, действительно.

2024-08-21 09:44 UTC, eugene-okulik approved these changes

2024-08-21 09:44 UTC, eugene-okulik commented on test_api_mandreevproj/conftest.py
> +    return response
Эта штука может сразу возвращать response.json()['id'] - так будет значительно проще пользоваться этой фикстурой.

2024-08-21 09:44 UTC, merged